//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.21 at 03:14:12 PM GMT+05:30 
//


package in.gov.uidai.srdh.portal.vo;



import java.text.SimpleDateFormat;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "enrollment")
public class Enrollment {

    @XmlAttribute(name = "addr-building")
    protected String addrBuilding="";
    @XmlAttribute(name = "addr-building-local")
    protected String addrBuildingLocal="";
    @XmlAttribute(name = "addr-careof")
    protected String addrCareof="";
    @XmlAttribute(name = "addr-careof-local")
    protected String addrCareofLocal="";
    @XmlAttribute(name = "addr-district-name")
    protected String addrDistrictName="";
    @XmlAttribute(name = "addr-district-name-local")
    protected String addrDistrictNameLocal="";
    @XmlAttribute(name = "addr-landmark")
    protected String addrLandmark="";
    @XmlAttribute(name = "addr-landmark-local")
    protected String addrLandmarkLocal="";
    @XmlAttribute(name = "addr-locality")
    protected String addrLocality="";
    @XmlAttribute(name = "addr-locality-local")
    protected String addrLocalityLocal="";
    @XmlAttribute(name = "addr-pincode")
    protected String addrPincode="";
    @XmlAttribute(name = "addr-po-name")
    protected String addrPoName="";
    @XmlAttribute(name = "addr-po-name-local")
    protected String addrPoNameLocal="";
    @XmlAttribute(name = "addr-state-name")
    protected String addrStateName="";
    @XmlAttribute(name = "addr-state-name-local")
    protected String addrStateNameLocal="";
    @XmlAttribute(name = "addr-street")
    protected String addrStreet="";
    @XmlAttribute(name = "addr-street-local")
    protected String addrStreetLocal="";
    @XmlAttribute(name = "addr-vtc-name")
    protected String addrVtcName="";
    @XmlAttribute(name = "addr-vtc-name-local")
    protected String addrVtcNameLocal="";
    @XmlAttribute
    protected Date dob;
    @XmlAttribute(name = "dob-year")
    protected String dobYear="";
    @XmlAttribute(required = true)
    protected String eid="";
    @XmlAttribute
    protected String email="";
    @XmlAttribute
    protected String gender="";
    @XmlAttribute
    protected String mobile="";
    @XmlAttribute
    protected String name="";
    @XmlAttribute(name = "name-local")
    protected String nameLocal="";
    @XmlAttribute(required = true)
    protected String uid="";
    @XmlAttribute
    protected  byte[] photo;  
    @XmlAttribute
    protected String enrollmentnumber="";  
    @XmlAttribute(name = "error")
    protected String error;
    
    private EnrollmentDetails enrolmentdetails;
    
    
    public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	public EnrollmentDetails getEnrolmentdetails() {
		return enrolmentdetails;
	}

    public void setEnrolmentdetails(EnrollmentDetails enrolmentdetailsTemp) {
		if(enrolmentdetailsTemp!=null){
			this.setPhoto(enrolmentdetailsTemp.getPhoto());
		}
		else
		{
			this.setPhoto(null);
		}
	}

	/**
     * Gets the value of the addrBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrBuilding() {
        return addrBuilding;
    }

    /**
     * Sets the value of the addrBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrBuilding(String value) {
        this.addrBuilding = value;
    }

    /**
     * Gets the value of the addrBuildingLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrBuildingLocal() {
        return addrBuildingLocal;
    }

    /**
     * Sets the value of the addrBuildingLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrBuildingLocal(String value) {
        this.addrBuildingLocal = value;
    }

    /**
     * Gets the value of the addrCareof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrCareof() {
        return addrCareof;
    }

    /**
     * Sets the value of the addrCareof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrCareof(String value) {
        this.addrCareof = value;
    }

    /**
     * Gets the value of the addrCareofLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrCareofLocal() {
        return addrCareofLocal;
    }

    /**
     * Sets the value of the addrCareofLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrCareofLocal(String value) {
        this.addrCareofLocal = value;
    }

    /**
     * Gets the value of the addrDistrictName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrDistrictName() {
        return addrDistrictName;
    }

    /**
     * Sets the value of the addrDistrictName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrDistrictName(String value) {
        this.addrDistrictName = value;
    }

    /**
     * Gets the value of the addrDistrictNameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrDistrictNameLocal() {
        return addrDistrictNameLocal;
    }

    /**
     * Sets the value of the addrDistrictNameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrDistrictNameLocal(String value) {
        this.addrDistrictNameLocal = value;
    }

    /**
     * Gets the value of the addrLandmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLandmark() {
        return addrLandmark;
    }

    /**
     * Sets the value of the addrLandmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLandmark(String value) {
        this.addrLandmark = value;
    }

    /**
     * Gets the value of the addrLandmarkLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLandmarkLocal() {
        return addrLandmarkLocal;
    }

    /**
     * Sets the value of the addrLandmarkLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLandmarkLocal(String value) {
        this.addrLandmarkLocal = value;
    }

    /**
     * Gets the value of the addrLocality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLocality() {
        return addrLocality;
    }

    /**
     * Sets the value of the addrLocality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLocality(String value) {
        this.addrLocality = value;
    }

    /**
     * Gets the value of the addrLocalityLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrLocalityLocal() {
        return addrLocalityLocal;
    }

    /**
     * Sets the value of the addrLocalityLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrLocalityLocal(String value) {
        this.addrLocalityLocal = value;
    }

    /**
     * Gets the value of the addrPincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrPincode() {
        return addrPincode;
    }

    /**
     * Sets the value of the addrPincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrPincode(String value) {
        this.addrPincode = value;
    }

    /**
     * Gets the value of the addrPoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrPoName() {
        return addrPoName;
    }

    /**
     * Sets the value of the addrPoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrPoName(String value) {
        this.addrPoName = value;
    }

    /**
     * Gets the value of the addrPoNameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrPoNameLocal() {
        return addrPoNameLocal;
    }

    /**
     * Sets the value of the addrPoNameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrPoNameLocal(String value) {
        this.addrPoNameLocal = value;
    }

    /**
     * Gets the value of the addrStateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrStateName() {
        return addrStateName;
    }

    /**
     * Sets the value of the addrStateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrStateName(String value) {
        this.addrStateName = value;
    }

    /**
     * Gets the value of the addrStateNameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrStateNameLocal() {
        return addrStateNameLocal;
    }

    /**
     * Sets the value of the addrStateNameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrStateNameLocal(String value) {
        this.addrStateNameLocal = value;
    }

    /**
     * Gets the value of the addrStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrStreet() {
        return addrStreet;
    }

    /**
     * Sets the value of the addrStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrStreet(String value) {
        this.addrStreet = value;
    }

    /**
     * Gets the value of the addrStreetLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrStreetLocal() {
        return addrStreetLocal;
    }

    /**
     * Sets the value of the addrStreetLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrStreetLocal(String value) {
        this.addrStreetLocal = value;
    }

    /**
     * Gets the value of the addrVtcName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrVtcName() {
        return addrVtcName;
    }

    /**
     * Sets the value of the addrVtcName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrVtcName(String value) {
        this.addrVtcName = value;
    }

    /**
     * Gets the value of the addrVtcNameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrVtcNameLocal() {
        return addrVtcNameLocal;
    }

    /**
     * Sets the value of the addrVtcNameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrVtcNameLocal(String value) {
        this.addrVtcNameLocal = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDob() {
       return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDob(Date value) {
    	
        this.dob = value;
    }


    /**
     * Gets the value of the dobYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDobYear() {
        return dobYear;
    }

    /**
     * Sets the value of the dobYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDobYear(String value) {
        this.dobYear = value;
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEid() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEid(String value) {
        this.eid = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }
    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }
    /**
     * Gets the value of the mobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameLocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocal() {
        return nameLocal;
    }

    /**
     * Sets the value of the nameLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocal(String value) {
        this.nameLocal = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

	public byte[] getPhoto() 
	{
		if(photo == null)
		{
			this.photo = new byte[]{};
			return this.photo;
		}
		
		return photo;
	}

	public void setPhoto(byte[] photo) 
	{
		if(photo == null)
			this.photo = new byte[]{};
		else
			this.photo = photo;
	}

	public String getEnrollmentnumber() {
		return enrollmentnumber;
	}

	public void setEnrollmentnumber(String enrollmentnumber) {
		this.enrollmentnumber = enrollmentnumber;
	}

}
