//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 08:41:06 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uidai.gov.in/SRDH/SearchResults", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.gov.uidai.srdh.portal.vo;
